export const START_ACT = "START_ACTION";
export const STOP_ACT = "STOP_ACTION";
export const TASKCOMPLETE_ACT = "TASK_COMPLETED_ACTION";
export const SET_TASK_DURATION_ACT = "SET_TASK_DURATION_ACTION";